image: alpine:latest

services:
- docker:dind

stages:
- build
- test
- check
- release

variables:
  TEST_IMAGE: registry.gitlab.com/atanu007/container_nginx:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE: registry.gitlab.com/atanu007/container_nginx:latest

before_script:
  - sudo docker login -u Atanu007 -p redhat@123 gitlab.com

build:
  stage: build
  script:
    - sudo docker build --pull -t $TEST_IMAGE .
    - sudo docker push $TEST_IMAGE

test:
  stage: test
  script:
    - sudo docker pull $TEST_IMAGE
    - mkdir nginx
    - sudo docker-compose up -d  
    - sleep 10s
    - sudo docker ps

check:
  stage: check
  script:
    - curl http://localhost:8099

release:
  stage: release
  script:
    - sudo docker pull $TEST_IMAGE
    - sudo docker tag $TEST_IMAGE $RELEASE_IMAGE
    - sudo docker push $RELEASE_IMAGE
  only:
    - master  
