image: alpine:latest

services:
- docker:dind

stages:
- build
- test
- release

variables:
  TEST_IMAGE: registry.gitlab.com/atanu007/container_nginx:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE: registry.gitlab.com/atanu007/container_nginx:latest

before_script:
  - docker login -u Atanu007 -p redhat@123 gitlab.com

build:
  stage: build
  script:
    - docker build -t $TEST_IMAGE .
    - docker push $TEST_IMAGE

test:
  stage: test
  script:
    - docker pull $TEST_IMAGE
    - docker-compose up -d  
    - sleep 10s
    - docker ps

release:
  stage: release
  script:
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
  only:
    - master  
